version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
  settings:
    gofmt:
      simplify: true
    misspell:
      locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
